apps/blog/urls.py
from django.conf.urls import url
from django.contrib.auth.views import password_change

from . import views


urlpatterns = [
    url(r'^$', views.discussions, name='discussions_page'),
    url(r'^register/$', views.registration, name='registration_page'),
    url(r'^discussions/(?P<title_id>[0-9]+)/$', views.detail_discussions,
        name='detail_discussions'),
    url(r'^main/$', views.main_page, name='main_page'),
    url(r'^home/$', views.home_page, name='home_page'),
    url(r'^profile/$', views.profile, name='profile_page'),
    url(r'^password_change/$', password_change, {
        'post_change_redirect': 'auth:password_change_done'},
        name='password_change'),
    url(r'^add_discussions/$',
        views.add_discussions, name='add_discussions_page')
]

core/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = [
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^auth/', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^comments/', include('django_comments.urls')),
]

apps/blog/models.py
from __future__ import unicode_literals
import datetime

from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _


class Note(models.Model):
    author = models.ForeignKey('auth.User', verbose_name=_(u'Author'),
                               blank=True, null=True)
    title = models.CharField(max_length=100)
    pub_date = models.DateTimeField('date published', default=timezone.now)
    text = models.TextField()

    def __unicode__(self):
        return unicode(self.title)

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = _('Published recently?')

    @models.permalink
    def get_absolute_url(self):
        return 'blog:detail_discussions', (), {'title_id': self.pk}

apps/blog/forms.py
# -*- encoding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.forms import UserCreationForm as RegistrationForm
from .models import Note


class UserCreationForm(RegistrationForm):
    email = forms.EmailField(label=_(u'E-mail'))

    class Meta:
        model = User
        fields = (
            'username', 'email', 'password1', 'password2'
        )

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                _(u'This email address is already taken. '
                  u'Please adjust your selection.'))

        return email

    def save(self, *args, **kwargs):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.save()
        return user


class AddNotesForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = (
            'title', 'text'
        )

    def clean_title(self):
        title = self.cleaned_data['title']
        if Note.objects.filter(title=title).exists():
            raise forms.ValidationError(
                _(u'This title is already taken. '))

        return title

apps/blog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth import login as login_user, authenticate
from django.shortcuts import get_object_or_404, render

from .forms import UserCreationForm, AddNotesForm
from .models import Note


def registration(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        user = form.save()
        user = authenticate(username=user.username, password=user.password)
        if user and user.is_active:
            login_user(request, user)
        return redirect('blog:discussions_page')

    return render(
        request, 'registration/registration.html', {'form': form})


def main_page(request):
    return render(request, 'blog/main.html')


def detail_discussions(request, title_id):
    note = get_object_or_404(Note, pk=title_id)
    return render(request, 'blog/detail_discussion.html', {'note': note})


def discussions(request):
    latest_theme_list = Note.objects.filter(
        pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    context = {'latest_theme_list': latest_theme_list}
    return render(request, 'blog/discussions.html', context)


@login_required
def add_discussions(request):
    form = AddNotesForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.pub_date = timezone.now()
        post.save()
        return redirect('blog:discussions_page')
    return render(request, 'blog/add_discussions.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'blog/profile.html')


def home_page(request):
    return render(request, 'blog/home.html')

apps/blog/templates/blocks/errors.html
{% if field.errors %}
  <span class="error_label">
    {% for err in field.errors %}
      {{ err }}
    {% endfor %}
  </span>
{% endif %}

apps/blog/templates/blog/add_discussions.html
{% extends 'blog/base.html' %}
{% load static i18n %}

{% block content %}
  <div id="content">
    <form class="top_indent" action="" method="post">
      {% csrf_token %}
      <table>
        <tr>
          <th>
            <label for="id_name">{% trans 'Subject' %}:</label>
          </th>
          <td>
            {{ form.title }}
            {% include 'blocks/errors.html' with field=form.title %}
          </td>
        </tr>
        <tr>
          <th>
            <label for="id_email">{% trans 'Text' %}:</label>
          </th>
          <td>
            {{ form.text }}
          </td>
        </tr>
        <tr>
          <td>
            <input class="button" type="submit" name="submit" value={% trans 'Save' %}>
          </td>
        </tr>
      </table>
    </form>
  </div>
{% endblock %}

apps/blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
{% load comments %}
{% load i18n %}
<html>
<head>
<meta charset="utf-8">
  <title>{% trans 'Blog' %}</title>
  <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
  <script type="text/javascript" src="{% static "js/jquery-1.10.2.min.js" %}"></script>
  <script type="text/javascript" src="{% static "js/main.js" %}"></script>
</head>
<body>
  <div id="display">
    <header id="header">
      <a href="{% url 'blog:home_page' %}"><img class="logo" src="{% static 'images/logo.png' %}" /></a>
      {% if user.is_authenticated %}
        <a class="link" href="{% url 'auth:logout' %}?next={% url 'auth:login' %}">{% trans 'Logout' %}</a>
        <a class="link" href="{% url 'blog:profile_page' %}">{% trans 'Profile' %}</a>
        <a class="link" href="{% url 'blog:add_discussions_page' %}">{% trans 'Add post' %}</a>
      {% else %}
        <a class="link" href="{% url 'auth:login' %}">{% trans 'Login' %}</a>
        <a class="link" href="{% url 'blog:registration_page' %}">{% trans 'Registration' %}</a>
      {% endif %}
      <a class="link" href="{% url 'blog:discussions_page' %}">{% trans 'Discussions' %}</a>
    </header>

    {% block content %}{% endblock %}

    <footer class="footer">
      <div class="copyright">
	    © 2015-{{ settings.CURRENT_YEAR }} <a href="{% url 'blog:main_page' %}">{% trans 'Rimma Kupriianova' %}</a>
	  </div>
    </footer>
  </div>
</body>
</html>

apps/blog/templates/blog/detail_discussion.html
{% extends 'blog/base.html' %}
{% load static i18n %}
{% load comments %}
{% load url from future %}

{% block content %}
  <div id="content">
    <div>
      <h1 class="note_name">{{ note.title }}</h1>
      <p class="note_date">{% trans 'Published date' %}: {{ note.pub_date|date:"d.m.Y G:i" }} {% trans 'Author' %}: {{ note.author }}</p>
      <p class="note_text">{{ note.text }}</p>
    </div>
    <div class="all_comments">
      <p class="comments">{% trans 'Comments' %}</p>
      <div class="add_comments">
        {% get_comment_form for note as form %}
        <table>
          {% if user.is_authenticated %}
            <form action="{% comment_form_target %}" method="post">
              {% csrf_token %}
                <tr>
                  <th>
                    <label for="id_name">{% trans 'Username' %}:</label>
                  </th>
                  <td>
                    {{ form.name }}
                  </td>
                </tr>
                <tr>
                  <th>
                    <label for="id_email">{% trans 'Email address' %}:</label>
                  </th>
                  <td>
                    {{ form.email }}
                  </td>
                </tr>
                <tr>
                  <th>
                    <label for="id_comment">{% trans 'Comment' %}:</label>
                  </th>
                  <td>
                    {{ form.comment }}
                  </td>
                </tr>
              <tr>
                <td style="display: none">
                  {{ form.honeypot }}
                  {{ form.content_type }}
                  {{ form.object_pk }}
                  {{ form.timestamp }}
                  {{ form.security_hash }}
                </td>
              </tr>
              <tr>
                <td colspan="2">
                  <input class="button" type="submit" name="submit" value={% trans '' %}"Add comment">
                  <input type="hidden" name="next" value="{% url 'blog:detail_discussions' note.id %}" />
                </td>
              </tr>
            </form>
          {% endif %}
        </table>
      </div>
      {% get_comment_list for note as comment_list %}
      <table class="table">
        {% for comment in comment_list|dictsortreversed:"submit_date" %}
          <tr>
            <td rowspan="2">
              <img src="{% static 'images/avatar.jpg' %}" />
            </td>
            <td class="old_comment">
             {{ comment.submit_date|date:"d.m.Y G:i" }} {{ comment.name }}
            </td>
          </tr>
          <tr>
            <td id="comment">
              {{ comment.comment }}
            </td>
          </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock %}

apps/blog/templates/blog/discussions.html
{% extends 'blog/base.html' %}
{% load static i18n %}

{% block content %}
  <div id="content">
    <p class="topics">{% trans 'Topics for discussions' %}</p>
    {% if latest_theme_list %}
      <ul class="note_list">
        {% for note in latest_theme_list %}
            <li class="note"><a href="{{ note.get_absolute_url }}">{{ note.title }}</a></li>
        {% endfor %}
      </ul>
    {% else %}
      <p>No notes are available.</p>
    {% endif %}
  </div>
{% endblock %}

apps/blog/templates/blog/home.html
{% extends 'blog/base.html' %}
{% load static i18n %}

{% block content %}
  <div id="content">
    <div class="head">{% trans 'Welcome to the blog about programming' %}</div>
{#    <div id="main">#}
{#    </div>#}
  </div>
{% endblock %}

apps/blog/templates/blog/main.html
{% extends 'blog/base.html' %}
{% load static i18n %}

{% block content %}
  <div id="content">
    <div class="head">{% trans 'Main information about me' %}</div>
    <div id="main">
      <img src="{% static 'images/me.png' %}" width="200px" height="272px"/>
        <h1 class="autob">{% trans 'My autobiography' %}</h1>
        <p>
          I was born at 20 January 1989. Now I'm 26 years. I was educated
          in Kharkov Institute of Finance in 2011. My specialty according to
          Diploma is the financier.  After education I went to work in the Department
          of the Kharkov City Council. But having worked there not a long time, I quited.
        </p>
        <p>
          I didn't like my job and decided to change the scope of the activities.
          This helped me <a href="https://ua.linkedin.com/in/serhii-k-02231b64"> my brother</a>.
          And in 2014 I met first with HTML and then with javascript. My first
          experience in the programming was bubble game ans then online game(slot machines).
        </p>
        <p>
          Then I was lucky and I began to work in a broker company.
          I worked there from March 2015 to November 2015. I have implemented a new
          functionality with Django's templates, edited the existing code and added the
          styles and JS, worked with MySQL, with version control system Git. And now I am in search of work.
          I have experience with DjangoCMS, javascript, CCS, HTML, PostgreSQL and MySQL.
        </p>
        <p>

        </p>


{#      <p><b>{% trans 'Last Name First Name:' %}</b> <span>{% trans 'Kupriianova Rimma' %}</span></p>#}
{#      <p><b>{% trans 'Date of Birth:' %}</b> <span>{% trans '20 January 1989 Year' %}</span></p>#}
{#      <p><b>{% trans 'Country:' %}</b> <span>{% trans 'Ukraine' %}</span></p>#}
{#      <p><b>{% trans 'City:' %}</b> <span>{% trans 'Kharkov' %}</span></p>#}
{#      <p><b>{% trans 'Contacts:' %}</b></p>#}
      <p>Skype: ssoffitt; email: asiwija@gmail.com</p>
    </div>
  </div>
{% endblock %}

apps/blog/templates/blog/profile.html
{% extends 'blog/base.html' %}
{% load static i18n %}

{% block content %}
  <div id="content" class="header">
    <table class="profile">
      <tr>
        <th>
          <label for="id_username">{% trans 'Username' %}:</label>
        </th>
        <td>
          {{ user.username }}
        </td>
      </tr>
      <tr>
        <th>
          <label for="id_email">{% trans 'Email address' %}:</label>
        </th>
        <td>
          {{ user.email }}
        </td>
      </tr>
      <tr>
        <th>
          <label for="id_date_joined">{% trans 'Registration date' %}:</label>
        </th>
        <td>
          {{ user.date_joined|date:"d.m.Y" }}
        </td>
      </tr>
      <tr>
        <th>
          <label for="id_last_login">{% trans 'Last login' %}:</label>
        </th>
        <td>
          {{ user.last_login|date:"d.m.Y" }}
        </td>
      </tr>
    </table>
    <a href="{% url 'blog:password_change' %}" class="link pass">{% trans 'Change password' %}</a>
  </div>
{% endblock %}